#!/bin/bash
# run-build-ucvm

source setup/setup_cvm_web.sh

mkdir -p $UCVM_TOP_DIR
mkdir -p $UCVM_INSTALL_PATH

cd $UCVM_TOP_DIR
#git clone https://github.com/SCECcode/ucvm.git -b withSFCVM src
git clone https://github.com/SCECcode/ucvm.git src


cd $UCVM_SRC_PATH/largefiles
./get_largefiles.py -m wfcvm,cca,sfcvm,cvms,cvmsi,cvms5,cvmh,ivlsu,cvlsu,albacore,sjfz,cvmhlabn,cvmhsgbn,cvmhvbn,cvmhibbn,cvmhrbn,cvmhsbbn,cvmhsbcbn,cvmhsmbn,cvmhstbn,canvas,uwsfbcvm,uwlinca,cs248,muscal,muscal2,uwpkfcvm,sjqbn
./check_largefiles_md5.py
./stage_largefiles.py

### for system that has really old gcc
### TileDB needs this..
#This is for linux/moho
if command -v gcc10-gcc &> /dev/null; then
  echo "gcc10-gcc exists"
  export CC=gcc10-gcc
  export CXX=gcc10-g++
else
  if command -v gcc-10 &> /dev/null; then
    echo "gcc-10 exists"
    export CC=gcc-10
    export CXX=g++-10
  else
    echo "use default gcc"
  fi
fi

export PYTHONUNBUFFERED=TRUE
cd $UCVM_SRC_PATH
./ucvm_setup.py -a -f -d -p $UCVM_INSTALL_PATH &> ucvm_setup_install.log 

#can not run this while in docker compose's build because largedata dir is not mounted yet
#echo "running runcheck .."
#cd $UCVM_SRC_PATH; source conf/ucvm_env.sh; make runcheck

## make sure everything in installed model is globally readable
chmod -R og+r $UCVM_INSTALL_PATH/model
echo "..done run-build-ucvm.."
